language: node_js

cache:
  directories:
    - ~/.npm
    
node_js:
  - '10'

install:
  - npm ci --no-optional
  - npm i -g codecov

script:
  - npm run test:prod && npm run build

after_success:
  - codecov --file=coverage/lcov.info --disable=search,gcov
